name: sample-dockerfile
region: fra
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: teamcoherence/sample-dockerfile
  http_port: 9998
  name: sample-dockerfile
