name: sample-dockerfile
region: fra
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: teamcoherence/do-apache-tika-docker
  http_port: 9998
  name: do-apache-tika-docker
